import { AUTO_PARTICIPANT_PROFILE_OPTIONS, formatAutoParticipantProfile, formatAutoParticipantProfileBehavior, formatAutoParticipantProfileDescription } from "@/app/lib/autoParticipantProfiles";
import { AdminAutoParticipantCards, type AutoParticipantEditDraft, type AutoParticipantEditDraftSetters } from "@/app/supply-demand/admin/AdminAutoParticipantCards";
import { RECURRING_CASH_INTERVAL_UNIT_OPTIONS } from "@/app/supply-demand/admin/AdminConstants";
import { formatAutoIntensityDirection } from "@/app/supply-demand/admin/AdminFormatters";
import { DarkInput, DarkSelect, EnabledToggleButton } from "@/app/supply-demand/admin/AdminFormControls";
import type { AutoParticipant, AutoParticipantOverview, AutoParticipantProfileType, AutoParticipantSymbolConfig, RecurringCashIntervalUnit } from "@/app/types/stock";

type ParticipantStatusFilter = "ALL" | "ENABLED" | "DISABLED";
type AutoGenerateProfileMode = "ROTATE" | "SINGLE";

type AdminAutoParticipantManagementPanelProps = {
  isEditing: boolean;
  participantUserKey: string;
  draft: AutoParticipantEditDraft;
  draftSetters: AutoParticipantEditDraftSetters;
  saving: boolean;
  selectedParticipant: AutoParticipant | null;
  selectedSymbolConfigs: AutoParticipantSymbolConfig[];
  strategySymbols: string[];
  strategyUserKey: string;
  strategySymbol: string;
  strategyEnabled: boolean;
  strategyIntensity: string;
  editingStrategyKey: string | null;
  selectedStrategyKey: string;
  savingStrategy: boolean;
  togglingStrategyKey: string | null;
  autoGenerateCount: string;
  autoGenerateKeyPrefix: string;
  autoGenerateDisplayPrefix: string;
  autoGenerateProfileMode: AutoGenerateProfileMode;
  autoGenerateProfileType: AutoParticipantProfileType;
  generatingAutoParticipants: boolean;
  participantSearch: string;
  participantStatusFilter: ParticipantStatusFilter;
  participantProfileFilter: "ALL" | AutoParticipantProfileType;
  filteredParticipantCount: number;
  totalParticipantCount: number;
  participantPageStart: number;
  participantPageEnd: number;
  participantTotalPages: number;
  boundedParticipantPage: number;
  visibleParticipants: AutoParticipant[];
  overviewByUserKey: ReadonlyMap<string, AutoParticipantOverview>;
  editingUserKey: string | null;
  togglingUserKey: string | null;
  withdrawingUserKey: string | null;
  adjustingCashType: "DEPOSIT" | "WITHDRAW" | null;
  overviewsFetching: boolean;
  onParticipantUserKeyChange: (value: string) => void;
  onSubmitParticipant: () => void;
  onResetParticipantDraft: () => void;
  onSelectStrategySymbol: (userKey: string, symbol: string) => void;
  onClearStrategy: (userKey: string) => void;
  onStrategyEnabledChange: (enabled: boolean) => void;
  onStrategyIntensityChange: (value: string) => void;
  onSubmitStrategy: () => void;
  onToggleStrategyEnabled: (config: AutoParticipantSymbolConfig) => void;
  onSelectStrategyDraft: (config: AutoParticipantSymbolConfig) => void;
  onAutoGenerateCountChange: (value: string) => void;
  onAutoGenerateKeyPrefixChange: (value: string) => void;
  onAutoGenerateDisplayPrefixChange: (value: string) => void;
  onAutoGenerateProfileModeChange: (value: AutoGenerateProfileMode) => void;
  onAutoGenerateProfileTypeChange: (value: AutoParticipantProfileType) => void;
  onGenerateParticipants: () => void;
  onParticipantSearchChange: (value: string) => void;
  onParticipantStatusFilterChange: (value: ParticipantStatusFilter) => void;
  onParticipantProfileFilterChange: (value: "ALL" | AutoParticipantProfileType) => void;
  onParticipantPageChange: (updater: (page: number) => number) => void;
  onToggleParticipant: (participant: AutoParticipant) => void;
  onSelectParticipant: (participant: AutoParticipant) => void;
  onWithdrawParticipant: (participant: AutoParticipant) => void;
  onAdjustCash: (adjustmentType: "DEPOSIT" | "WITHDRAW") => void;
};

export function AdminAutoParticipantManagementPanel({
  isEditing,
  participantUserKey,
  draft,
  draftSetters,
  saving,
  selectedParticipant,
  selectedSymbolConfigs,
  strategySymbols,
  strategyUserKey,
  strategySymbol,
  strategyEnabled,
  strategyIntensity,
  editingStrategyKey,
  selectedStrategyKey,
  savingStrategy,
  togglingStrategyKey,
  autoGenerateCount,
  autoGenerateKeyPrefix,
  autoGenerateDisplayPrefix,
  autoGenerateProfileMode,
  autoGenerateProfileType,
  generatingAutoParticipants,
  participantSearch,
  participantStatusFilter,
  participantProfileFilter,
  filteredParticipantCount,
  totalParticipantCount,
  participantPageStart,
  participantPageEnd,
  participantTotalPages,
  boundedParticipantPage,
  visibleParticipants,
  overviewByUserKey,
  editingUserKey,
  togglingUserKey,
  withdrawingUserKey,
  adjustingCashType,
  overviewsFetching,
  onParticipantUserKeyChange,
  onSubmitParticipant,
  onResetParticipantDraft,
  onSelectStrategySymbol,
  onClearStrategy,
  onStrategyEnabledChange,
  onStrategyIntensityChange,
  onSubmitStrategy,
  onToggleStrategyEnabled,
  onSelectStrategyDraft,
  onAutoGenerateCountChange,
  onAutoGenerateKeyPrefixChange,
  onAutoGenerateDisplayPrefixChange,
  onAutoGenerateProfileModeChange,
  onAutoGenerateProfileTypeChange,
  onGenerateParticipants,
  onParticipantSearchChange,
  onParticipantStatusFilterChange,
  onParticipantProfileFilterChange,
  onParticipantPageChange,
  onToggleParticipant,
  onSelectParticipant,
  onWithdrawParticipant,
  onAdjustCash,
}: AdminAutoParticipantManagementPanelProps) {
  return (
    <section className="mt-5 rounded-lg border border-white/10 bg-white/[0.06] p-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="text-base font-black">자동 참여자</h2>
          <p className="mt-1 text-xs font-bold text-[#8b95a1]">
            {isEditing
              ? "선택한 참여자의 프로필과 가동 상태를 수정 중입니다. 새 참여자는 신규 등록으로 전환해 입력합니다."
              : "참여자 등록은 프로필과 가동 상태만 저장하고, 운용 현금은 선택 후 입금/회수로 조정합니다."}
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          {isEditing ? (
            <button type="button" onClick={onResetParticipantDraft} className="rounded-md border border-white/10 bg-white/10 px-3 py-2 text-xs font-black text-white">
              신규 등록
            </button>
          ) : null}
        </div>
      </div>

      <div className="mt-4 grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-[1.1fr_1.2fr_1.1fr_0.8fr_0.9fr_0.75fr_0.75fr_auto]">
        <DarkInput label="참여자 키" value={participantUserKey} onChange={onParticipantUserKeyChange} placeholder="stock-auto-001" disabled={isEditing} />
        <DarkInput label="표시명" value={draft.displayName} onChange={draftSetters.setDisplayName} placeholder="자동 참여자 1" />
        <DarkSelect label="심리 프로필" value={draft.profileType} onChange={(value) => draftSetters.setProfileType(value as AutoParticipantProfileType)}>
          {AUTO_PARTICIPANT_PROFILE_OPTIONS.map((profile) => (
            <option key={profile.value} value={profile.value}>{profile.label}</option>
          ))}
        </DarkSelect>
        <DarkSelect label="상태" value={draft.enabled ? "true" : "false"} onChange={(value) => draftSetters.setEnabled(value === "true")}>
          <option value="true">가동</option>
          <option value="false">정지</option>
        </DarkSelect>
        <DarkInput label="개별 월급/현금" value={draft.recurringCashDisabled ? "" : draft.recurringCashAmount} onChange={draftSetters.setRecurringCashAmount} placeholder={draft.recurringCashDisabled ? "배당 이벤트만 사용" : "비우면 프로필"} disabled={draft.recurringCashDisabled} />
        <DarkInput label="주기 값" value={draft.recurringCashDisabled ? "" : draft.recurringCashIntervalValue} onChange={draftSetters.setRecurringCashIntervalValue} placeholder={draft.recurringCashDisabled ? "-" : "0.5"} disabled={draft.recurringCashDisabled} />
        <DarkSelect label="주기 단위" value={draft.recurringCashDisabled ? "DAY" : draft.recurringCashIntervalUnit} onChange={(value) => draftSetters.setRecurringCashIntervalUnit(value as RecurringCashIntervalUnit)} disabled={draft.recurringCashDisabled}>
          {RECURRING_CASH_INTERVAL_UNIT_OPTIONS.map((option) => (
            <option key={option.value} value={option.value}>{option.label}</option>
          ))}
        </DarkSelect>
        <button type="button" onClick={onSubmitParticipant} disabled={saving} className="min-h-11 min-w-0 self-end rounded-md bg-white px-3 py-3 text-sm font-black text-[#101418] disabled:opacity-50 sm:col-span-2 lg:col-span-1">
          {saving ? "저장 중" : isEditing ? "상태 저장" : "등록"}
        </button>
      </div>

      <div className="mt-3 rounded-md bg-black/20 px-3 py-3 text-xs font-bold leading-5 text-[#b8c2cc]">
        <span className="text-white">{formatAutoParticipantProfile(draft.profileType)}</span>
        <span className="mx-2 text-[#5a6572]">/</span>
        <span>{formatAutoParticipantProfileDescription(draft.profileType)}</span>
        <span className="mx-2 text-[#5a6572]">/</span>
        <span>{formatAutoParticipantProfileBehavior(draft.profileType)}</span>
      </div>

      {selectedParticipant ? (
        <div className="mt-4 rounded-lg border border-white/10 bg-black/20 p-3">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <p className="text-sm font-black text-white">종목별 가격 방향/강도</p>
              <p className="mt-1 text-xs font-bold text-[#8b95a1]">
                {selectedParticipant.displayName}에게만 적용되는 종목 강도입니다. 강도 10은 매수 우위, 1은 매도 우위로 계산됩니다.
              </p>
            </div>
            <span className="rounded-md bg-white/10 px-2 py-1 text-xs font-black text-[#64a8ff]">
              {selectedSymbolConfigs.length.toLocaleString("ko-KR")}개 설정
            </span>
          </div>
          <div className="mt-3 grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-[1fr_0.8fr_0.8fr_0.9fr_auto]">
            <DarkSelect
              label="종목"
              value={strategyUserKey === selectedParticipant.userKey ? strategySymbol : ""}
              onChange={(value) => {
                if (!value) {
                  onClearStrategy(selectedParticipant.userKey);
                  return;
                }
                onSelectStrategySymbol(selectedParticipant.userKey, value);
              }}
            >
              <option value="">선택</option>
              {strategySymbols.map((symbol) => (
                <option key={symbol} value={symbol}>{symbol}</option>
              ))}
            </DarkSelect>
            <DarkSelect label="가동 상태" value={strategyEnabled ? "true" : "false"} onChange={(value) => onStrategyEnabledChange(value === "true")}>
              <option value="true">가동</option>
              <option value="false">정지</option>
            </DarkSelect>
            <DarkInput label="강도(1-10)" value={strategyIntensity} onChange={onStrategyIntensityChange} placeholder="10" />
            <div className="grid gap-1 text-xs font-bold text-[#b8c2cc]">
              가격 방향
              <div className="rounded-md border border-white/10 bg-[#161b21] px-3 py-3 text-sm font-black text-white">
                {formatAutoIntensityDirection(Number.parseInt(strategyIntensity, 10))}
              </div>
            </div>
            <button type="button" onClick={onSubmitStrategy} disabled={savingStrategy} className="min-h-11 self-end rounded-md bg-white px-3 py-3 text-sm font-black text-[#101418] disabled:opacity-50 sm:col-span-2 lg:col-span-1">
              {savingStrategy ? "저장 중" : editingStrategyKey === selectedStrategyKey ? "강도 저장" : "강도 추가"}
            </button>
          </div>
          <div className="mt-3 overflow-x-auto rounded-md border border-white/10">
            <table className="min-w-[640px] w-full border-collapse text-sm">
              <thead className="bg-white/10 text-left text-[#b8c2cc]">
                <tr>
                  <th className="px-3 py-2">종목</th>
                  <th className="px-3 py-2">상태</th>
                  <th className="px-3 py-2">가격 방향</th>
                  <th className="px-3 py-2">강도</th>
                  <th className="px-3 py-2">수정</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/10">
                {selectedSymbolConfigs.map((config) => {
                  const rowKey = `${config.userKey}:${config.symbol}`;
                  return (
                    <tr key={rowKey} className={editingStrategyKey === rowKey ? "bg-[#10233a]/50" : undefined}>
                      <td className="px-3 py-2 font-black">{config.symbol}</td>
                      <td className="px-3 py-2">
                        <EnabledToggleButton
                          enabled={config.enabled}
                          disabled={togglingStrategyKey === rowKey}
                          onToggle={() => onToggleStrategyEnabled(config)}
                        />
                      </td>
                      <td className="px-3 py-2">{formatAutoIntensityDirection(config.intensity)}</td>
                      <td className="px-3 py-2 tabular-nums">{config.intensity}/10</td>
                      <td className="px-3 py-2">
                        <button type="button" onClick={() => onSelectStrategyDraft(config)} className="rounded-md bg-white/10 px-2 py-1 text-xs font-black text-white">
                          값 불러오기
                        </button>
                      </td>
                    </tr>
                  );
                })}
                {selectedSymbolConfigs.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="px-3 py-4 text-[#8b95a1]">이 참여자에게 지정된 종목별 강도가 없습니다. 종목을 선택해 추가하세요.</td>
                  </tr>
                ) : null}
              </tbody>
            </table>
          </div>
        </div>
      ) : null}

      {!isEditing ? (
        <div className="mt-4 rounded-lg border border-white/10 bg-black/20 p-3">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <p className="text-sm font-black text-white">자동 생성</p>
              <p className="mt-1 text-xs font-bold text-[#8b95a1]">다음 번호부터 참여자를 여러 명 만들고, 심리 프로필을 순서대로 분산하거나 하나의 프로필로 고정합니다.</p>
            </div>
            <span className="rounded-md bg-white/10 px-2 py-1 text-xs font-black text-[#64a8ff]">계좌/현금은 기존 흐름 유지</span>
          </div>
          <div className="mt-3 grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-[0.7fr_1fr_1fr_0.9fr_1.2fr_auto]">
            <DarkInput label="생성 인원" value={autoGenerateCount} onChange={onAutoGenerateCountChange} placeholder="5" />
            <DarkInput label="키 접두어" value={autoGenerateKeyPrefix} onChange={onAutoGenerateKeyPrefixChange} placeholder="stock-auto-" />
            <DarkInput label="표시명 접두어" value={autoGenerateDisplayPrefix} onChange={onAutoGenerateDisplayPrefixChange} placeholder="자동 참여자" />
            <DarkSelect label="프로필 적용" value={autoGenerateProfileMode} onChange={(value) => onAutoGenerateProfileModeChange(value as AutoGenerateProfileMode)}>
              <option value="ROTATE">순서 분산</option>
              <option value="SINGLE">단일 프로필</option>
            </DarkSelect>
            <DarkSelect
              label="단일 프로필"
              value={autoGenerateProfileType}
              onChange={(value) => onAutoGenerateProfileTypeChange(value as AutoParticipantProfileType)}
              disabled={autoGenerateProfileMode !== "SINGLE"}
            >
              {AUTO_PARTICIPANT_PROFILE_OPTIONS.map((profile) => (
                <option key={profile.value} value={profile.value}>{profile.label}</option>
              ))}
            </DarkSelect>
            <button
              type="button"
              onClick={onGenerateParticipants}
              disabled={generatingAutoParticipants || saving}
              className="min-h-11 self-end rounded-md bg-[#3182f6] px-3 py-3 text-sm font-black text-white disabled:cursor-wait disabled:opacity-55 sm:col-span-2 lg:col-span-1"
            >
              {generatingAutoParticipants ? "생성 중" : "자동 등록"}
            </button>
          </div>
        </div>
      ) : null}

      <div className="mt-4 grid min-w-0 grid-cols-1 gap-3 rounded-md border border-white/10 bg-black/20 p-3 sm:grid-cols-[minmax(0,1.4fr)_minmax(0,0.8fr)_minmax(0,1fr)]">
        <DarkInput
          label="참여자 검색"
          value={participantSearch}
          onChange={onParticipantSearchChange}
          placeholder="표시명 또는 userKey"
        />
        <DarkSelect
          label="상태 필터"
          value={participantStatusFilter}
          onChange={(value) => onParticipantStatusFilterChange(value as ParticipantStatusFilter)}
        >
          <option value="ALL">전체</option>
          <option value="ENABLED">가동</option>
          <option value="DISABLED">정지</option>
        </DarkSelect>
        <DarkSelect
          label="프로필 필터"
          value={participantProfileFilter}
          onChange={(value) => onParticipantProfileFilterChange(value as "ALL" | AutoParticipantProfileType)}
        >
          <option value="ALL">전체 프로필</option>
          {AUTO_PARTICIPANT_PROFILE_OPTIONS.map((profile) => (
            <option key={profile.value} value={profile.value}>{profile.label}</option>
          ))}
        </DarkSelect>
        <div className="flex min-w-0 flex-wrap items-center justify-between gap-2 text-xs font-bold text-[#8b95a1] sm:col-span-3">
          <p>
            표시 {filteredParticipantCount.toLocaleString("ko-KR")}명 / 전체 {totalParticipantCount.toLocaleString("ko-KR")}명
            {filteredParticipantCount > 0 ? ` · 현재 ${participantPageStart.toLocaleString("ko-KR")}-${participantPageEnd.toLocaleString("ko-KR")}` : ""}
          </p>
          {participantTotalPages > 1 ? (
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => onParticipantPageChange((page) => Math.max(0, page - 1))}
                disabled={boundedParticipantPage === 0}
                className="min-h-8 rounded-md bg-white/10 px-3 py-1.5 text-xs font-black text-white disabled:cursor-not-allowed disabled:opacity-40"
              >
                이전
              </button>
              <span className="tabular-nums text-[#b8c2cc]">
                {(boundedParticipantPage + 1).toLocaleString("ko-KR")} / {participantTotalPages.toLocaleString("ko-KR")}
              </span>
              <button
                type="button"
                onClick={() => onParticipantPageChange((page) => Math.min(participantTotalPages - 1, page + 1))}
                disabled={boundedParticipantPage >= participantTotalPages - 1}
                className="min-h-8 rounded-md bg-white/10 px-3 py-1.5 text-xs font-black text-white disabled:cursor-not-allowed disabled:opacity-40"
              >
                다음
              </button>
            </div>
          ) : null}
        </div>
      </div>

      <AdminAutoParticipantCards
        participants={visibleParticipants}
        overviewByUserKey={overviewByUserKey}
        editingUserKey={editingUserKey}
        togglingUserKey={togglingUserKey}
        withdrawingUserKey={withdrawingUserKey}
        saving={saving}
        adjustingCashType={adjustingCashType}
        overviewsFetching={overviewsFetching}
        draft={draft}
        draftSetters={draftSetters}
        onToggleParticipant={onToggleParticipant}
        onSelectParticipant={onSelectParticipant}
        onWithdrawParticipant={onWithdrawParticipant}
        onSubmitParticipant={onSubmitParticipant}
        onResetDraft={onResetParticipantDraft}
        onAdjustCash={onAdjustCash}
      />
    </section>
  );
}
