import { AUTO_PARTICIPANT_PROFILE_OPTIONS } from "@/app/lib/autoParticipantProfiles";
import { DarkInput, DarkSelect } from "@/app/supply-demand/admin/AdminFormControls";
import { RECURRING_CASH_INTERVAL_UNIT_OPTIONS } from "@/app/supply-demand/admin/AdminConstants";
import type { AutoGenerateProfileMode } from "@/app/supply-demand/admin/AdminAutoParticipantManagementTypes";
import type { AutoParticipantProfileType, RecurringCashIntervalUnit } from "@/app/types/stock";

type AdminAutoParticipantGeneratePanelProps = {
  isEditing: boolean;
  saving: boolean;
  autoGenerateCount: string;
  autoGenerateCreateAccount: boolean;
  autoGenerateKeyPrefix: string;
  autoGenerateDisplayPrefix: string;
  autoGenerateInitialCashAmount: string;
  autoGenerateProfileMode: AutoGenerateProfileMode;
  autoGenerateProfileType: AutoParticipantProfileType;
  autoGenerateRecurringCashAmount: string;
  autoGenerateRecurringCashIntervalUnit: RecurringCashIntervalUnit;
  autoGenerateRecurringCashIntervalValue: string;
  generatingAutoParticipants: boolean;
  onAutoGenerateCountChange: (value: string) => void;
  onAutoGenerateCreateAccountChange: (value: boolean) => void;
  onAutoGenerateKeyPrefixChange: (value: string) => void;
  onAutoGenerateDisplayPrefixChange: (value: string) => void;
  onAutoGenerateInitialCashAmountChange: (value: string) => void;
  onAutoGenerateProfileModeChange: (value: AutoGenerateProfileMode) => void;
  onAutoGenerateProfileTypeChange: (value: AutoParticipantProfileType) => void;
  onAutoGenerateRecurringCashAmountChange: (value: string) => void;
  onAutoGenerateRecurringCashIntervalUnitChange: (value: RecurringCashIntervalUnit) => void;
  onAutoGenerateRecurringCashIntervalValueChange: (value: string) => void;
  onGenerateParticipants: () => void;
};

export function AdminAutoParticipantGeneratePanel({
  isEditing,
  saving,
  autoGenerateCount,
  autoGenerateCreateAccount,
  autoGenerateKeyPrefix,
  autoGenerateDisplayPrefix,
  autoGenerateInitialCashAmount,
  autoGenerateProfileMode,
  autoGenerateProfileType,
  autoGenerateRecurringCashAmount,
  autoGenerateRecurringCashIntervalUnit,
  autoGenerateRecurringCashIntervalValue,
  generatingAutoParticipants,
  onAutoGenerateCountChange,
  onAutoGenerateCreateAccountChange,
  onAutoGenerateKeyPrefixChange,
  onAutoGenerateDisplayPrefixChange,
  onAutoGenerateInitialCashAmountChange,
  onAutoGenerateProfileModeChange,
  onAutoGenerateProfileTypeChange,
  onAutoGenerateRecurringCashAmountChange,
  onAutoGenerateRecurringCashIntervalUnitChange,
  onAutoGenerateRecurringCashIntervalValueChange,
  onGenerateParticipants,
}: AdminAutoParticipantGeneratePanelProps) {
  if (isEditing) {
    return null;
  }

  return (
    <div className="mt-4 rounded-lg border border-white/10 bg-black/20 p-3">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-sm font-black text-white">자동 생성</p>
          <p className="mt-1 text-xs font-bold text-stock-subtle">다음 번호부터 참여자를 여러 명 만들고, 계좌·초기 현금·월급 설정을 같은 규칙으로 적용합니다.</p>
        </div>
        <span className="rounded-md bg-white/10 px-2 py-1 text-xs font-black text-admin-accent">계좌/현금/월급 일괄 설정</span>
      </div>
      <div className="mt-3 grid min-w-0 gap-3">
        <div className="grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-5">
          <DarkInput label="생성 인원" value={autoGenerateCount} onChange={onAutoGenerateCountChange} placeholder="5" />
          <DarkInput label="키 접두어" value={autoGenerateKeyPrefix} onChange={onAutoGenerateKeyPrefixChange} placeholder="stock-auto-" />
          <DarkInput label="표시명 접두어" value={autoGenerateDisplayPrefix} onChange={onAutoGenerateDisplayPrefixChange} placeholder="자동 참여자" />
          <DarkSelect label="프로필 적용" value={autoGenerateProfileMode} onChange={(value) => onAutoGenerateProfileModeChange(value as AutoGenerateProfileMode)}>
            <option value="ROTATE">순서 분산</option>
            <option value="SINGLE">단일 프로필</option>
          </DarkSelect>
          <DarkSelect
            label="단일 프로필"
            value={autoGenerateProfileType}
            onChange={(value) => onAutoGenerateProfileTypeChange(value as AutoParticipantProfileType)}
            disabled={autoGenerateProfileMode !== "SINGLE"}
          >
            {AUTO_PARTICIPANT_PROFILE_OPTIONS.map((profile) => (
              <option key={profile.value} value={profile.value}>{profile.label}</option>
            ))}
          </DarkSelect>
        </div>
        <div className="grid min-w-0 grid-cols-1 gap-3 rounded-md border border-white/10 bg-white/[0.04] p-3 sm:grid-cols-2 lg:grid-cols-4">
          <label className="flex min-h-11 min-w-0 items-center gap-2 rounded-md border border-white/10 bg-admin-surface px-3 py-2 text-xs font-black text-[#d7e2ec]">
            <input
              type="checkbox"
              checked={autoGenerateCreateAccount}
              onChange={(event) => onAutoGenerateCreateAccountChange(event.target.checked)}
              className="h-4 w-4 rounded border-white/20 bg-admin-canvas accent-stock-accent"
            />
            <span className="min-w-0">계좌 즉시 생성</span>
          </label>
          <DarkInput label="초기 현금" value={autoGenerateInitialCashAmount} onChange={onAutoGenerateInitialCashAmountChange} placeholder="10000000" />
          <DarkInput label="월급/정기 현금" value={autoGenerateRecurringCashAmount} onChange={onAutoGenerateRecurringCashAmountChange} placeholder="비우면 프로필" />
          <DarkInput label="월급 주기 값" value={autoGenerateRecurringCashIntervalValue} onChange={onAutoGenerateRecurringCashIntervalValueChange} placeholder="30" />
          <DarkSelect
            label="월급 주기 단위"
            value={autoGenerateRecurringCashIntervalUnit}
            onChange={(value) => onAutoGenerateRecurringCashIntervalUnitChange(value as RecurringCashIntervalUnit)}
          >
            {RECURRING_CASH_INTERVAL_UNIT_OPTIONS.map((unit) => (
              <option key={unit.value} value={unit.value}>{unit.label}</option>
            ))}
          </DarkSelect>
          <p className="self-end text-xs font-bold leading-5 text-stock-subtle sm:col-span-2 lg:col-span-3">
            초기 현금을 입력하면 계좌 생성이 자동 적용됩니다. 배당재투자형은 월급 대신 배당 이벤트만 사용합니다.
          </p>
        </div>
        <div className="flex justify-end">
          <button
            type="button"
            onClick={onGenerateParticipants}
            disabled={generatingAutoParticipants || saving}
            className="min-h-11 w-full rounded-md bg-stock-accent px-4 py-3 text-sm font-black text-white disabled:cursor-wait disabled:opacity-55 sm:w-auto"
          >
            {generatingAutoParticipants ? "생성 중" : "자동 등록"}
          </button>
        </div>
      </div>
    </div>
  );
}
