import { AdminAutoParticipantCards, type AutoParticipantEditDraft, type AutoParticipantEditDraftSetters } from "@/app/supply-demand/admin/AdminAutoParticipantCards";
import { AdminAutoParticipantFormPanel } from "@/app/supply-demand/admin/AdminAutoParticipantFormPanel";
import { AdminAutoParticipantGeneratePanel } from "@/app/supply-demand/admin/AdminAutoParticipantGeneratePanel";
import { AdminAutoParticipantListFilterPanel } from "@/app/supply-demand/admin/AdminAutoParticipantListFilterPanel";
import type { AutoGenerateProfileMode, AutoParticipantListView } from "@/app/supply-demand/admin/AdminAutoParticipantManagementTypes";
import { AdminAutoParticipantStrategyPanel } from "@/app/supply-demand/admin/AdminAutoParticipantStrategyPanel";
import type { CashAdjustmentType } from "@/app/supply-demand/admin/AdminCashAdjustmentPayloadHelpers";
import type { AutoParticipant, AutoParticipantProfileType, AutoParticipantSymbolConfig, RecurringCashIntervalUnit } from "@/app/types/stock";

export type { AutoGenerateProfileMode, ParticipantProfileFilter, ParticipantStatusFilter } from "@/app/supply-demand/admin/AdminAutoParticipantManagementTypes";

export type AdminAutoParticipantManagementPanelProps = {
  isEditing: boolean;
  participantUserKey: string;
  draft: AutoParticipantEditDraft;
  draftSetters: AutoParticipantEditDraftSetters;
  saving: boolean;
  selectedParticipant: AutoParticipant | null;
  selectedSymbolConfigs: AutoParticipantSymbolConfig[];
  strategySymbols: string[];
  strategyUserKey: string;
  strategySymbol: string;
  strategyEnabled: boolean;
  strategyIntensity: string;
  editingStrategyKey: string | null;
  selectedStrategyKey: string;
  savingStrategy: boolean;
  togglingStrategyKey: string | null;
  autoGenerateCount: string;
  autoGenerateCreateAccount: boolean;
  autoGenerateKeyPrefix: string;
  autoGenerateDisplayPrefix: string;
  autoGenerateInitialCashAmount: string;
  autoGenerateProfileMode: AutoGenerateProfileMode;
  autoGenerateProfileType: AutoParticipantProfileType;
  autoGenerateRecurringCashAmount: string;
  autoGenerateRecurringCashIntervalUnit: RecurringCashIntervalUnit;
  autoGenerateRecurringCashIntervalValue: string;
  generatingAutoParticipants: boolean;
  participantList: AutoParticipantListView;
  editingUserKey: string | null;
  togglingUserKey: string | null;
  withdrawingUserKey: string | null;
  adjustingCashType: CashAdjustmentType | null;
  onParticipantUserKeyChange: (value: string) => void;
  onSubmitParticipant: () => void;
  onResetParticipantDraft: () => void;
  onSelectStrategySymbol: (userKey: string, symbol: string) => void;
  onClearStrategy: (userKey: string) => void;
  onStrategyEnabledChange: (enabled: boolean) => void;
  onStrategyIntensityChange: (value: string) => void;
  onSubmitStrategy: () => void;
  onToggleStrategyEnabled: (config: AutoParticipantSymbolConfig) => void;
  onSelectStrategyDraft: (config: AutoParticipantSymbolConfig) => void;
  onAutoGenerateCountChange: (value: string) => void;
  onAutoGenerateCreateAccountChange: (value: boolean) => void;
  onAutoGenerateKeyPrefixChange: (value: string) => void;
  onAutoGenerateDisplayPrefixChange: (value: string) => void;
  onAutoGenerateInitialCashAmountChange: (value: string) => void;
  onAutoGenerateProfileModeChange: (value: AutoGenerateProfileMode) => void;
  onAutoGenerateProfileTypeChange: (value: AutoParticipantProfileType) => void;
  onAutoGenerateRecurringCashAmountChange: (value: string) => void;
  onAutoGenerateRecurringCashIntervalUnitChange: (value: RecurringCashIntervalUnit) => void;
  onAutoGenerateRecurringCashIntervalValueChange: (value: string) => void;
  onGenerateParticipants: () => void;
  onToggleParticipant: (participant: AutoParticipant) => void;
  onSelectParticipant: (participant: AutoParticipant) => void;
  onWithdrawParticipant: (participant: AutoParticipant) => void;
  onAdjustCash: (adjustmentType: CashAdjustmentType) => void;
};

export function AdminAutoParticipantManagementPanel({
  isEditing,
  participantUserKey,
  draft,
  draftSetters,
  saving,
  selectedParticipant,
  selectedSymbolConfigs,
  strategySymbols,
  strategyUserKey,
  strategySymbol,
  strategyEnabled,
  strategyIntensity,
  editingStrategyKey,
  selectedStrategyKey,
  savingStrategy,
  togglingStrategyKey,
  autoGenerateCount,
  autoGenerateCreateAccount,
  autoGenerateKeyPrefix,
  autoGenerateDisplayPrefix,
  autoGenerateInitialCashAmount,
  autoGenerateProfileMode,
  autoGenerateProfileType,
  autoGenerateRecurringCashAmount,
  autoGenerateRecurringCashIntervalUnit,
  autoGenerateRecurringCashIntervalValue,
  generatingAutoParticipants,
  participantList,
  editingUserKey,
  togglingUserKey,
  withdrawingUserKey,
  adjustingCashType,
  onParticipantUserKeyChange,
  onSubmitParticipant,
  onResetParticipantDraft,
  onSelectStrategySymbol,
  onClearStrategy,
  onStrategyEnabledChange,
  onStrategyIntensityChange,
  onSubmitStrategy,
  onToggleStrategyEnabled,
  onSelectStrategyDraft,
  onAutoGenerateCountChange,
  onAutoGenerateCreateAccountChange,
  onAutoGenerateKeyPrefixChange,
  onAutoGenerateDisplayPrefixChange,
  onAutoGenerateInitialCashAmountChange,
  onAutoGenerateProfileModeChange,
  onAutoGenerateProfileTypeChange,
  onAutoGenerateRecurringCashAmountChange,
  onAutoGenerateRecurringCashIntervalUnitChange,
  onAutoGenerateRecurringCashIntervalValueChange,
  onGenerateParticipants,
  onToggleParticipant,
  onSelectParticipant,
  onWithdrawParticipant,
  onAdjustCash,
}: AdminAutoParticipantManagementPanelProps) {
  return (
    <section className="admin-panel mt-5">
      <AdminAutoParticipantFormPanel
        isEditing={isEditing}
        participantUserKey={participantUserKey}
        draft={draft}
        draftSetters={draftSetters}
        saving={saving}
        onParticipantUserKeyChange={onParticipantUserKeyChange}
        onSubmitParticipant={onSubmitParticipant}
        onResetParticipantDraft={onResetParticipantDraft}
      />

      <AdminAutoParticipantStrategyPanel
        selectedParticipant={selectedParticipant}
        selectedSymbolConfigs={selectedSymbolConfigs}
        strategySymbols={strategySymbols}
        strategyUserKey={strategyUserKey}
        strategySymbol={strategySymbol}
        strategyEnabled={strategyEnabled}
        strategyIntensity={strategyIntensity}
        editingStrategyKey={editingStrategyKey}
        selectedStrategyKey={selectedStrategyKey}
        savingStrategy={savingStrategy}
        togglingStrategyKey={togglingStrategyKey}
        onSelectStrategySymbol={onSelectStrategySymbol}
        onClearStrategy={onClearStrategy}
        onStrategyEnabledChange={onStrategyEnabledChange}
        onStrategyIntensityChange={onStrategyIntensityChange}
        onSubmitStrategy={onSubmitStrategy}
        onToggleStrategyEnabled={onToggleStrategyEnabled}
        onSelectStrategyDraft={onSelectStrategyDraft}
      />

      <AdminAutoParticipantGeneratePanel
        isEditing={isEditing}
        saving={saving}
        autoGenerateCount={autoGenerateCount}
        autoGenerateCreateAccount={autoGenerateCreateAccount}
        autoGenerateKeyPrefix={autoGenerateKeyPrefix}
        autoGenerateDisplayPrefix={autoGenerateDisplayPrefix}
        autoGenerateInitialCashAmount={autoGenerateInitialCashAmount}
        autoGenerateProfileMode={autoGenerateProfileMode}
        autoGenerateProfileType={autoGenerateProfileType}
        autoGenerateRecurringCashAmount={autoGenerateRecurringCashAmount}
        autoGenerateRecurringCashIntervalUnit={autoGenerateRecurringCashIntervalUnit}
        autoGenerateRecurringCashIntervalValue={autoGenerateRecurringCashIntervalValue}
        generatingAutoParticipants={generatingAutoParticipants}
        onAutoGenerateCountChange={onAutoGenerateCountChange}
        onAutoGenerateCreateAccountChange={onAutoGenerateCreateAccountChange}
        onAutoGenerateKeyPrefixChange={onAutoGenerateKeyPrefixChange}
        onAutoGenerateDisplayPrefixChange={onAutoGenerateDisplayPrefixChange}
        onAutoGenerateInitialCashAmountChange={onAutoGenerateInitialCashAmountChange}
        onAutoGenerateProfileModeChange={onAutoGenerateProfileModeChange}
        onAutoGenerateProfileTypeChange={onAutoGenerateProfileTypeChange}
        onAutoGenerateRecurringCashAmountChange={onAutoGenerateRecurringCashAmountChange}
        onAutoGenerateRecurringCashIntervalUnitChange={onAutoGenerateRecurringCashIntervalUnitChange}
        onAutoGenerateRecurringCashIntervalValueChange={onAutoGenerateRecurringCashIntervalValueChange}
        onGenerateParticipants={onGenerateParticipants}
      />

      <AdminAutoParticipantListFilterPanel
        controls={participantList.controls}
        list={participantList}
      />

      <AdminAutoParticipantCards
        participants={participantList.visibleParticipants}
        overviewByUserKey={participantList.overviewByUserKey}
        editingUserKey={editingUserKey}
        togglingUserKey={togglingUserKey}
        withdrawingUserKey={withdrawingUserKey}
        saving={saving}
        adjustingCashType={adjustingCashType}
        overviewsFetching={participantList.overviewsFetching}
        draft={draft}
        draftSetters={draftSetters}
        onToggleParticipant={onToggleParticipant}
        onSelectParticipant={onSelectParticipant}
        onWithdrawParticipant={onWithdrawParticipant}
        onSubmitParticipant={onSubmitParticipant}
        onResetDraft={onResetParticipantDraft}
        onAdjustCash={onAdjustCash}
      />
    </section>
  );
}
