const MARKET_ROLE_LABELS: Readonly<Record<string, string>> = {
  LIVE: "실운영",
  ACTIVE: "운영 중",
  SUSPENDED: "중단",
  EXPIRED: "만료",
  CLOSED: "종료",
  ALLOCATED: "인수 배정 완료",
  STABILIZING: "유한 공급 중",
  COMPLETED: "완료",
  CANCELLED: "취소",
  CLAIMED: "처리 중",
  PENDING: "대기",
  SUBMITTED: "주문 제출",
  REJECTED: "거절",
  FAILED: "실패",
  QUOTING: "호가 운영 중",
  EXEMPT: "호가 일시 대기",
  HALTED: "안전 중단",
  ERROR: "오류",
  GATED: "제한 적용",
  SKIPPED: "건너뜀",
  BUY: "매수",
  SELL: "매도",
  HOLD: "보유 유지",
  BALANCED_LONG_TERM: "연기금·저회전 균형형",
  VALUE_CONTRARIAN: "가치·역추세형",
  MOMENTUM: "모멘텀형",
  ACTIVE_SHORT_TERM: "단기 적극운용형",
  LIQUIDITY_PROVIDER: "유동성 공급자",
  ISSUE_UNDERWRITER: "발행 인수기관",
  INSTITUTIONAL_INVESTOR: "기관 투자자",
  SYSTEM_CUSTODY: "시스템 보관계정",
  AUTO_PARTICIPANT: "자동 참여자",
  MANUAL_PARTICIPANT: "일반 참여자",
  LISTING_UNDERWRITER: "기존 상장주관 계정",
  FIRM_COMMITMENT: "총액 인수",
  BEST_EFFORTS: "모집 주선",
  TRADABLE: "거래 가능",
  LOCKED: "거래 잠금",
  LIVE_ACTIVE: "실운영 중",
  INITIAL_ISSUE: "최초 발행",
  CAPITAL_INCREASE: "유상증자",
  LOCK_RELEASE: "잠금 해제",
  MANUAL_REALLOCATION: "관리자 재배정",
  INITIAL_FLOAT_CUSTODY: "최초 유통 대기 보관",
  INITIAL_FLOAT_UNDERWRITER: "최초 유통분 인수",
  INITIAL_LOCKED_CUSTODY: "최초 잠금 물량 보관",
  PUBLIC_ALLOCATION: "일반 청약 배정",
  UNSOLD_UNDERWRITING: "미매각 물량 인수",
  CORPORATE_ACTION_ALLOCATION: "기업행사 배정",
  LIQUIDITY_SEED_TRANSFER: "유동성 공급 시드 이전",
  LIQUIDITY_ACCOUNT_TRANSFER: "기존 유동성 계좌 이전",
  ALREADY_CREATED: "이미 생성됨",
  LIQUIDITY_SOURCE_REQUIRED: "이전 가능한 유동성 재고 계정 필요",
  SOURCE_ACCOUNT_REQUIRED: "사용 가능한 출발 계정 필요",
  SOURCE_INVENTORY_SHORTAGE: "출발 계정의 가용 재고 부족",
  PENDING_LISTING_REQUIRED: "역할 분리형 상장 대기 종목 아님",
  FLOAT_CUSTODY_REQUIRED: "유통 대기 보관계정 필요",
  FLOAT_CUSTODY_SHORTAGE: "유통 대기 보관수량 부족",
  READY: "생성 가능",
  NOT_RUN: "아직 실행 전",
  NOT_DUE: "실행 시각 전",
  WITHIN_LIMITS: "한도 이내",
  TARGET_COVERED: "목표 호가 충족",
  HYSTERESIS_BAND: "목표 허용구간 안",
  TARGET_DEFICIT: "목표 비중 부족",
  TARGET_SURPLUS: "목표 비중 초과",
  NO_ASSET: "운용자산 없음",
  NO_PRICE: "유효 가격 없음",
  PASSED: "위험 점검 통과",
  ADMIN_SUSPENDED: "관리자 중단",
  ADMIN_RESUMED_PREOPEN: "장전 관리자 재개",
  POLICY_UPDATED_PREOPEN: "장전 정책 변경",
  CONTRACT_NOT_ACTIVE: "계약 비활성",
  MARKET_NOT_AVAILABLE: "시장 이용 불가",
  MARKET_NOT_ENABLED: "시장 비활성",
  MARKET_CONFIG_INVALID: "시장 설정 오류",
  INVALID_EXECUTION_MODE: "실행 방식 오류",
  NON_PASSIVE_POLICY_NOT_SUPPORTED: "수동 지정가 외 정책 미지원",
  PREVIOUS_HARD_LIMIT_BREACH: "이전 하드 한도 초과",
  POLICY_CHANGED_DURING_SESSION: "장중 정책 변경 감지",
  DAILY_STATE_INCONSISTENT: "거래일 상태 불일치",
  OPEN_ORDER_SCAN_LIMIT_EXCEEDED: "미체결 주문 점검 한도 초과",
  EXTERNAL_BOOK_CROSSED: "외부 호가 역전",
  INVALID_CURRENT_PRICE: "현재가 오류",
  INVALID_QUOTE_PRICE: "호가 가격 오류",
  SUBMISSION_LIMIT_BREACHED: "제출 한도 초과",
  SUBMISSION_LIMIT_REACHED: "제출 한도 도달",
  DAILY_SUBMISSION_LIMIT_REACHED: "일일 제출 한도 도달",
  DAILY_ORDER_LIMIT_REACHED: "일일 주문 건수 한도 도달",
  EXECUTION_LIMIT_REACHED: "체결 한도 도달",
  OPEN_EXPOSURE_OVER_EXECUTION_LIMIT: "미체결 포함 체결 여력 소진",
  LOSS_LIMIT_REACHED: "손실 한도 도달",
  EXTERNAL_DEPTH_TOO_THIN: "외부 호가 깊이 부족",
  INVENTORY_BAND_REACHED: "재고 밴드 도달",
  INSUFFICIENT_CASH: "가용 현금 부족",
  INSUFFICIENT_INVENTORY: "가용 재고 부족",
  NO_NEW_QUOTE_CAPACITY: "신규 호가 여력 없음",
  SUPPLY_RECONCILIATION_FAILED: "공급 수량 대사 실패",
  ROLE_RECONCILIATION_FAILED: "전용 역할 대사 실패",
  SUPPLY_POLICY_INCOMPLETE: "공급 정책 미완성",
  WINDOW_NOT_STARTED: "공급 기간 시작 전",
  WINDOW_ENDED: "공급 기간 종료",
  OPEN_ORDER_RECONCILIATION_FAILED: "미체결 주문 대사 실패",
  OPEN_ORDER_OVERFLOW: "미체결 주문 수 초과",
  INVALID_OPEN_ORDER_SIDE: "미체결 주문 방향 오류",
  EXPIRED_ORDER_CANCELLED: "만료 주문 취소",
  LIFETIME_LIMIT_PENDING_OPEN_ORDER: "계약 총한도 내 미체결 주문 유지",
  OPEN_ORDER_RETAINED: "기존 미체결 주문 유지",
  LIFETIME_LIMIT_REACHED: "계약 총한도 도달",
  REFERENCE_VOLUME_MISSING: "기준 거래량 없음",
  PASSIVE_PRICE_UNAVAILABLE: "수동 지정가 산정 불가",
  NO_SUPPLY_CAPACITY: "추가 공급 여력 없음",
  PORTFOLIO_NOT_ACTIVE_LIVE: "기관 포트폴리오 운영 중 아님",
  ACCOUNT_ROLE_INVALID: "기관 전용 계정 역할 오류",
  PARTICIPANT_MAPPING_INVALID: "기관·계좌 역할 매핑 오류",
  SELF_TRADE_GROUP_MISMATCH: "자기체결 방지 그룹 불일치",
  INTENT_CONTRACT_INVALID: "주문 의도 계약 오류",
  SINGLE_ORDER_LIMIT_EMPTY: "단일 주문 한도 없음",
  EXECUTION_PRICE_OR_DEPTH_UNAVAILABLE: "체결 가격 또는 호가 깊이 없음",
  AGGRESSIVE_PRICE_OUTSIDE_DAILY_LIMIT: "공격 주문 가격이 일일 한도 밖",
  PLANNED_NOTIONAL_LIMIT_EMPTY: "계획 주문금액 한도 없음",
  PASSIVE_PRICE_WOULD_CROSS: "수동 지정가가 상대 호가 침범",
  AGGRESSIVE_WITHIN_15_PERCENT_CAP: "허용 범위 내 제한적 공격 주문",
  PASSIVE_LIMIT: "수동 지정가",
  ACTIVE_MARKET_CONFIG_MISSING: "활성 시장 설정 없음",
  ACCOUNT_NOT_ELIGIBLE: "전용 계정 상태 또는 역할 오류",
  PARTICIPANT_NOT_ELIGIBLE: "기관 상태 또는 유형 오류",
  ROLE_MAPPING_NOT_EFFECTIVE: "기관·계좌 역할의 효력 없음",
  ROLE_DESK_SYMBOL_MISMATCH: "담당 종목과 계약 종목 불일치",
  INVALID_INVENTORY_STATE: "재고 또는 예약수량 오류",
  INVALID_CASH_STATE: "현금 잔액 오류",
  NON_LP_OPEN_ORDER_ON_DEDICATED_ACCOUNT: "전용 계정에 LP 소유가 아닌 미체결 주문 존재",
  UNMANAGED_HOLDING_ON_DEDICATED_ACCOUNT: "전용 계정에 담당 외 종목 보유",
  ROLE_MAPPING_MISMATCH: "기관·계좌 역할 매핑 불일치",
  SYMBOL_MISMATCH: "종목 불일치",
};

export function formatMarketRoleCode(
  value: string | null | undefined,
  emptyLabel = "미설정",
  unknownLabel = "상세 상태 확인 필요",
) {
  if (!value) {
    return emptyLabel;
  }
  const known = MARKET_ROLE_LABELS[value];
  if (known) {
    return known;
  }
  if (value.startsWith("ADMIN_EMERGENCY_SUSPEND:")) {
    const reason = value.slice("ADMIN_EMERGENCY_SUSPEND:".length).trim();
    return reason ? `관리자 긴급 중단: ${reason}` : "관리자 긴급 중단";
  }
  return /[A-Za-z]/.test(value) ? unknownLabel : value;
}
