import { useState } from "react";

import { AdminAutoParticipantCards, type AutoParticipantEditDraft, type AutoParticipantEditDraftSetters } from "@/app/supply-demand/admin/AdminAutoParticipantCards";
import { AdminAutoParticipantFormPanel } from "@/app/supply-demand/admin/AdminAutoParticipantFormPanel";
import { AdminAutoParticipantGeneratePanel } from "@/app/supply-demand/admin/AdminAutoParticipantGeneratePanel";
import { AdminAutoParticipantListFilterPanel } from "@/app/supply-demand/admin/AdminAutoParticipantListFilterPanel";
import type { AutoGenerateProfileMode, AutoParticipantListView } from "@/app/supply-demand/admin/AdminAutoParticipantManagementTypes";
import { AdminAutoParticipantStrategyPanel } from "@/app/supply-demand/admin/AdminAutoParticipantStrategyPanel";
import type { CashAdjustmentType } from "@/app/supply-demand/admin/AdminCashAdjustmentPayloadHelpers";
import type { AutoParticipant, AutoParticipantProfileType, AutoParticipantSymbolConfig, RecurringCashIntervalUnit } from "@/app/types/stock";

export type { AutoGenerateProfileMode, ParticipantProfileFilter, ParticipantStatusFilter } from "@/app/supply-demand/admin/AdminAutoParticipantManagementTypes";

export type AdminAutoParticipantManagementPanelProps = {
  isEditing: boolean;
  participantUserKey: string;
  draft: AutoParticipantEditDraft;
  draftSetters: AutoParticipantEditDraftSetters;
  saving: boolean;
  selectedParticipant: AutoParticipant | null;
  selectedSymbolConfigs: AutoParticipantSymbolConfig[];
  strategySymbols: string[];
  strategyUserKey: string;
  strategySymbol: string;
  strategyEnabled: boolean;
  strategyIntensity: string;
  editingStrategyKey: string | null;
  selectedStrategyKey: string;
  savingStrategy: boolean;
  togglingStrategyKey: string | null;
  autoGenerateCount: string;
  autoGenerateCreateAccount: boolean;
  autoGenerateKeyPrefix: string;
  autoGenerateDisplayPrefix: string;
  autoGenerateInitialCashAmount: string;
  autoGenerateProfileMode: AutoGenerateProfileMode;
  autoGenerateProfileType: AutoParticipantProfileType;
  autoGenerateRecurringCashAmount: string;
  autoGenerateRecurringCashIntervalUnit: RecurringCashIntervalUnit;
  autoGenerateRecurringCashIntervalValue: string;
  generatingAutoParticipants: boolean;
  participantList: AutoParticipantListView;
  editingUserKey: string | null;
  togglingUserKey: string | null;
  withdrawingUserKey: string | null;
  adjustingCashType: CashAdjustmentType | null;
  onParticipantUserKeyChange: (value: string) => void;
  onSubmitParticipant: () => void;
  onResetParticipantDraft: () => void;
  onSelectStrategySymbol: (userKey: string, symbol: string) => void;
  onClearStrategy: (userKey: string) => void;
  onStrategyEnabledChange: (enabled: boolean) => void;
  onStrategyIntensityChange: (value: string) => void;
  onSubmitStrategy: () => void;
  onToggleStrategyEnabled: (config: AutoParticipantSymbolConfig) => void;
  onSelectStrategyDraft: (config: AutoParticipantSymbolConfig) => void;
  onAutoGenerateCountChange: (value: string) => void;
  onAutoGenerateCreateAccountChange: (value: boolean) => void;
  onAutoGenerateKeyPrefixChange: (value: string) => void;
  onAutoGenerateDisplayPrefixChange: (value: string) => void;
  onAutoGenerateInitialCashAmountChange: (value: string) => void;
  onAutoGenerateProfileModeChange: (value: AutoGenerateProfileMode) => void;
  onAutoGenerateProfileTypeChange: (value: AutoParticipantProfileType) => void;
  onAutoGenerateRecurringCashAmountChange: (value: string) => void;
  onAutoGenerateRecurringCashIntervalUnitChange: (value: RecurringCashIntervalUnit) => void;
  onAutoGenerateRecurringCashIntervalValueChange: (value: string) => void;
  onGenerateParticipants: () => void;
  onToggleParticipant: (participant: AutoParticipant) => void;
  onSelectParticipant: (participant: AutoParticipant) => void;
  onWithdrawParticipant: (participant: AutoParticipant) => void;
  onAdjustCash: (adjustmentType: CashAdjustmentType) => void;
};

export function AdminAutoParticipantManagementPanel({
  isEditing,
  participantUserKey,
  draft,
  draftSetters,
  saving,
  selectedParticipant,
  selectedSymbolConfigs,
  strategySymbols,
  strategyUserKey,
  strategySymbol,
  strategyEnabled,
  strategyIntensity,
  editingStrategyKey,
  selectedStrategyKey,
  savingStrategy,
  togglingStrategyKey,
  autoGenerateCount,
  autoGenerateCreateAccount,
  autoGenerateKeyPrefix,
  autoGenerateDisplayPrefix,
  autoGenerateInitialCashAmount,
  autoGenerateProfileMode,
  autoGenerateProfileType,
  autoGenerateRecurringCashAmount,
  autoGenerateRecurringCashIntervalUnit,
  autoGenerateRecurringCashIntervalValue,
  generatingAutoParticipants,
  participantList,
  editingUserKey,
  togglingUserKey,
  withdrawingUserKey,
  adjustingCashType,
  onParticipantUserKeyChange,
  onSubmitParticipant,
  onResetParticipantDraft,
  onSelectStrategySymbol,
  onClearStrategy,
  onStrategyEnabledChange,
  onStrategyIntensityChange,
  onSubmitStrategy,
  onToggleStrategyEnabled,
  onSelectStrategyDraft,
  onAutoGenerateCountChange,
  onAutoGenerateCreateAccountChange,
  onAutoGenerateKeyPrefixChange,
  onAutoGenerateDisplayPrefixChange,
  onAutoGenerateInitialCashAmountChange,
  onAutoGenerateProfileModeChange,
  onAutoGenerateProfileTypeChange,
  onAutoGenerateRecurringCashAmountChange,
  onAutoGenerateRecurringCashIntervalUnitChange,
  onAutoGenerateRecurringCashIntervalValueChange,
  onGenerateParticipants,
  onToggleParticipant,
  onSelectParticipant,
  onWithdrawParticipant,
  onAdjustCash,
}: AdminAutoParticipantManagementPanelProps) {
  const [workspace, setWorkspace] = useState<"DIRECTORY" | "CREATE" | "BULK" | "STRATEGY">("DIRECTORY");

  const startCreate = () => {
    onResetParticipantDraft();
    setWorkspace("CREATE");
  };

  const selectParticipant = (participant: AutoParticipant) => {
    onSelectParticipant(participant);
    setWorkspace("DIRECTORY");
  };

  return (
    <section className="admin-panel mt-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="text-base font-black">자동 참여자 관리</h2>
          <p className="mt-1 text-xs font-bold text-stock-subtle">조회·등록·대량 생성·종목 전략을 작업 단위로 나눠 필요한 정보만 표시합니다.</p>
        </div>
        {selectedParticipant ? <span className="rounded-md bg-admin-accent-surface px-2 py-1 text-xs font-black text-admin-accent">선택: {selectedParticipant.displayName}</span> : null}
      </div>

      <div className="mt-4 grid grid-cols-2 gap-2 rounded-md border border-white/10 bg-black/20 p-1 sm:grid-cols-4" role="tablist" aria-label="자동 참여자 작업">
        <WorkspaceTab active={workspace === "DIRECTORY"} onClick={() => setWorkspace("DIRECTORY")}>목록·수정</WorkspaceTab>
        <WorkspaceTab active={workspace === "CREATE"} onClick={startCreate}>신규 등록</WorkspaceTab>
        <WorkspaceTab active={workspace === "BULK"} onClick={() => setWorkspace("BULK")}>대량 생성</WorkspaceTab>
        <WorkspaceTab active={workspace === "STRATEGY"} disabled={!selectedParticipant} onClick={() => setWorkspace("STRATEGY")}>종목 전략</WorkspaceTab>
      </div>

      {workspace === "CREATE" ? (
        <div className="mt-4 rounded-md border border-white/10 bg-black/15 p-3">
          <AdminAutoParticipantFormPanel
            isEditing={false}
            participantUserKey={participantUserKey}
            draft={draft}
            draftSetters={draftSetters}
            saving={saving}
            onParticipantUserKeyChange={onParticipantUserKeyChange}
            onSubmitParticipant={onSubmitParticipant}
            onResetParticipantDraft={onResetParticipantDraft}
          />
        </div>
      ) : null}

      {workspace === "BULK" ? (
        <AdminAutoParticipantGeneratePanel
          isEditing={false}
          saving={saving}
          autoGenerateCount={autoGenerateCount}
          autoGenerateCreateAccount={autoGenerateCreateAccount}
          autoGenerateKeyPrefix={autoGenerateKeyPrefix}
          autoGenerateDisplayPrefix={autoGenerateDisplayPrefix}
          autoGenerateInitialCashAmount={autoGenerateInitialCashAmount}
          autoGenerateProfileMode={autoGenerateProfileMode}
          autoGenerateProfileType={autoGenerateProfileType}
          autoGenerateRecurringCashAmount={autoGenerateRecurringCashAmount}
          autoGenerateRecurringCashIntervalUnit={autoGenerateRecurringCashIntervalUnit}
          autoGenerateRecurringCashIntervalValue={autoGenerateRecurringCashIntervalValue}
          generatingAutoParticipants={generatingAutoParticipants}
          onAutoGenerateCountChange={onAutoGenerateCountChange}
          onAutoGenerateCreateAccountChange={onAutoGenerateCreateAccountChange}
          onAutoGenerateKeyPrefixChange={onAutoGenerateKeyPrefixChange}
          onAutoGenerateDisplayPrefixChange={onAutoGenerateDisplayPrefixChange}
          onAutoGenerateInitialCashAmountChange={onAutoGenerateInitialCashAmountChange}
          onAutoGenerateProfileModeChange={onAutoGenerateProfileModeChange}
          onAutoGenerateProfileTypeChange={onAutoGenerateProfileTypeChange}
          onAutoGenerateRecurringCashAmountChange={onAutoGenerateRecurringCashAmountChange}
          onAutoGenerateRecurringCashIntervalUnitChange={onAutoGenerateRecurringCashIntervalUnitChange}
          onAutoGenerateRecurringCashIntervalValueChange={onAutoGenerateRecurringCashIntervalValueChange}
          onGenerateParticipants={onGenerateParticipants}
        />
      ) : null}

      {workspace === "STRATEGY" ? (
        <AdminAutoParticipantStrategyPanel
          selectedParticipant={selectedParticipant}
          selectedSymbolConfigs={selectedSymbolConfigs}
          strategySymbols={strategySymbols}
          strategyUserKey={strategyUserKey}
          strategySymbol={strategySymbol}
          strategyEnabled={strategyEnabled}
          strategyIntensity={strategyIntensity}
          editingStrategyKey={editingStrategyKey}
          selectedStrategyKey={selectedStrategyKey}
          savingStrategy={savingStrategy}
          togglingStrategyKey={togglingStrategyKey}
          onSelectStrategySymbol={onSelectStrategySymbol}
          onClearStrategy={onClearStrategy}
          onStrategyEnabledChange={onStrategyEnabledChange}
          onStrategyIntensityChange={onStrategyIntensityChange}
          onSubmitStrategy={onSubmitStrategy}
          onToggleStrategyEnabled={onToggleStrategyEnabled}
          onSelectStrategyDraft={onSelectStrategyDraft}
        />
      ) : null}

      {workspace === "DIRECTORY" ? (
        <>
          <AdminAutoParticipantListFilterPanel controls={participantList.controls} list={participantList} />
          {isEditing ? (
            <p className="mt-3 rounded-md border border-admin-accent/20 bg-admin-accent-surface px-3 py-2 text-xs font-bold text-admin-accent-label">
              선택한 참여자의 수정 폼은 해당 카드 안에 표시됩니다. 종목별 설정은 위의 ‘종목 전략’에서 관리하세요.
            </p>
          ) : null}
          <AdminAutoParticipantCards
            participants={participantList.visibleParticipants}
            overviewByUserKey={participantList.overviewByUserKey}
            editingUserKey={editingUserKey}
            togglingUserKey={togglingUserKey}
            withdrawingUserKey={withdrawingUserKey}
            saving={saving}
            adjustingCashType={adjustingCashType}
            overviewsFetching={participantList.overviewsFetching}
            draft={draft}
            draftSetters={draftSetters}
            onToggleParticipant={onToggleParticipant}
            onSelectParticipant={selectParticipant}
            onWithdrawParticipant={onWithdrawParticipant}
            onSubmitParticipant={onSubmitParticipant}
            onResetDraft={onResetParticipantDraft}
            onAdjustCash={onAdjustCash}
          />
        </>
      ) : null}
    </section>
  );
}

function WorkspaceTab({ active, disabled = false, onClick, children }: { active: boolean; disabled?: boolean; onClick: () => void; children: React.ReactNode }) {
  return (
    <button
      type="button"
      role="tab"
      aria-selected={active}
      disabled={disabled}
      onClick={onClick}
      className={[
        "min-h-10 rounded-sm px-3 py-2 text-xs font-black transition disabled:cursor-not-allowed disabled:opacity-35",
        active ? "bg-admin-accent text-admin-canvas" : "text-admin-muted hover:bg-white/[0.06] hover:text-white",
      ].join(" ")}
    >
      {children}
    </button>
  );
}
